[project]
name = "dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "google-adk>=1.15.1",
    "html2text>=2025.4.15",
    "httpx>=0.28.1",
    "mcp[cli]>=1.15.0",
]
